# Generated by Django 2.0 on 2020-12-13 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='profile_data',
            fields=[
                ('index', models.BigIntegerField(primary_key=True, serialize=False)),
                ('id', models.BigIntegerField()),
                ('Season', models.TextField(blank=True, max_length=50)),
                ('city', models.TextField(max_length=50)),
                ('date', models.TextField(max_length=150, unique=True)),
                ('team1', models.TextField()),
                ('team2', models.TextField()),
                ('toss_winner', models.TextField()),
                ('toss_decision', models.TextField()),
                ('result', models.TextField()),
                ('dl_applied', models.BigIntegerField()),
                ('winner', models.TextField()),
                ('win_by_runs', models.BigIntegerField()),
                ('win_by_wickets', models.BigIntegerField()),
                ('player_of_match', models.TextField()),
                ('venue', models.TextField(max_length=50)),
                ('umpire1', models.TextField(blank=True)),
                ('umpire2', models.TextField(blank=True)),
                ('umpire3', models.TextField(blank=True)),
            ],
        ),
    ]
